// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  alternate_grid: defineAsyncComponent(
    () => import("./AlternateGrid/index.vue"),
  ),
  customer_logos: defineAsyncComponent(
    () => import("./CustomerLogos/index.vue"),
  ),
  rich_text: defineAsyncComponent(() => import("./RichText/index.vue")),
  text: defineAsyncComponent(() => import("./Text/index.vue")),
});
